### PR TITLE
Add update check and self update option 

### LINKED ISSUE #779: add update flags to subfinder
### Proposed Changes

```console
UPDATE:
   -up, -update                 update subfinder to the latest version
   -duc, -disable-update-check  disable automatic update check
```

### Reference
https://github.com/projectdiscovery/pdtm/blob/87dc669d40186e990c988c5a0ee3940302814b8c/examples/main.go#L16-L32

### PR DESCRIPTION
**Pull request by RamanaReddy0M**
### Proposed Changes

- adds update flags
```console
UPDATE:
   -up, -update                 update subfinder to latest version
   -duc, -disable-update-check  disable automatic subfinder update check

```
- Reference: https://github.com/projectdiscovery/tlsx/blob/8038ac06765d490210aa8bf753f44758a653b39f/cmd/tlsx/main.go#L125

closes #779

### CODE REVIEW

**Review by tarunKoyalwar — COMMENTED** [review]
@RamanaReddy0M  is there a specific reason why you unquoted all strings ?? i.e

```
 `%s` => %s
```
if there is no specific reason I think we should revert that . Quoted strings in output gives us idea if value of xyz variable is whitespace or actually empty 

about update utils it lgtm !

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !

**Comment by ulises2k** [comment]
image

**[updater] failed to fetch latest release of subfinder**

**Comment by tarunKoyalwar** [comment]
@ulises2k  can you share output of `subfinder -update -v` ?? it will show the exact error that occured

**Comment by ulises2k** [comment]
image

**Comment by ulises2k** [comment]
image

**Pull request merged**
