### PR TITLE
recon.dev: fix token

### PR DESCRIPTION
**Pull request by sepehrdaddev**
recon.dev now requires a token.
this pr adds token handling of recon.dev
api docs are here: [API](https://recon.dev/api/docs)

### CODE REVIEW

**Comment by bauthard** [comment]
Hey @sepehrdaddev, 

I tried to run this with an invalid key in the config file and got the following error, this error is expected?

```sh
$ ./subfinder -d hackerone.com -sources recon -v

        _     __ _         _
____  _| |__ / _(_)_ _  __| |___ _ _
(_-< || | '_ \  _| | ' \/ _  / -_) '_|
/__/\_,_|_.__/_| |_|_||_\__,_\___|_| v2.4.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] By using subfinder, you also agree to the terms of the APIs used.

[INF] Enumerating subdomains for hackerone.com
[recon] Source took 1.319477773s for enumeration
[WRN] Could not run source recon: invalid character 'B' looking for beginning of value
[INF] Found 0 subdomains for hackerone.com in 1 second 319 milliseconds
```

**Comment by sepehrdaddev** [comment]
Hey @bauthard,
No it's not expected.
Could you please send the invalid code so that I could debug it ?

**Comment by bauthard** [comment]
I used the following @sepehrdaddev in the config file. 

```
recon:
    - aaaa
```

**Comment by sepehrdaddev** [comment]
@bauthard, cool.
I will debug it and fix the issue.

**Comment by sepehrdaddev** [comment]
@bauthard , I have found the error.
It's a mishandling on recon.dev which based on https://recon.dev/api/docs it says it will send 500 errors if key is not valid, however the server sends 200 status code.

**Comment by bauthard** [comment]
@sepehrdaddev, I don't valid key for confirmation, if it works with a valid key (if you can post SS for `subfinder -d hackerone.com -sources recon -v`, we can merge this.

**Pull request merged**
