### PR TITLE
Fix panic caused by bufferover

### PR DESCRIPTION
**Pull request by tevino**

### CODE REVIEW

**Comment by Ice3man543** [comment]
Hey @tevino, could you give me the stacktrace where the panic occurs in bufferover? I'd love to see the root cause!

**Comment by Ice3man543** [comment]
Okay, i know what is the root cause here! Let me fix that real soon. Thanks for notifying!

**Comment by tevino** [comment]
@Ice3man543 Of course, it's pretty straightforward if you look at the code.

```
> docker run --rm ice3man/subfinder -d <domain>

        _     __ _         _         
____  _| |__ / _(_)_ _  __| |___ _ _ 
(_-< || | '_ \  _| | ' \/ _  / -_) '_|
/__/\_,_|_.__/_| |_|_||_\__,_\___|_| v2

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] By using subfinder, you also agree to the terms of the APIs used.

[INF] Configuration file saved to /root/.config/subfinder/config.yaml
[INF] Enumerating subdomains for <domain>
panic: close of closed channel

goroutine 69 [running]:
github.com/projectdiscovery/subfinder/pkg/subscraping/sources/bufferover.(*Source).Run.func1(0xd34260, 0x7ffc66eddf3e, 0x9, 0xc00015c000, 0xc0000247e0)
	/go/src/github.com/projectdiscovery/subfinder/pkg/subscraping/sources/bufferover/bufferover.go:24 +0x171
created by github.com/projectdiscovery/subfinder/pkg/subscraping/sources/bufferover.(*Source).Run
	/go/src/github.com/projectdiscovery/subfinder/pkg/subscraping/sources/bufferover/bufferover.go:19 +0x89
```

**Comment by tevino** [comment]
I did some bold refactoring to make the package testable, it's now 100% covered, please take a look.

**Comment by Ice3man543** [comment]
@tevino true. It should be fixed. BTW, i really liked the way you structured those tests. At first, the package had tests, but i removed them because i thought too much network interaction in those tests. But yeah, i like those tests. Let me see if we can structure all the modules similarly!

**Comment by Ice3man543** [comment]
Hey @tevino, i had a look. IMO it would make more sense to perform the above changes on the subscraping package itself and make it an interface so that mocks can be implemented for testing as you did with the bufferover module here! I'll create a new issue for the same and mark it as `help-needed`. Would you be willing to make those changes in a new PR on the package level.

I'll go ahead and close this PR btw as this is already patched. let me know what are your thoughts on that issue!

**Pull request closed without merging**
