### PR TITLE
Initial adoption of golangci-lint for continuous integration

### PR DESCRIPTION
**Pull request by vzamanillo**
Implements #277

Needs revision, it should be set as a draft for further improvement before confirming the merge.

There are several linters that I have disabled because for now it is a lot of work to correct the errors, for example

- `funlen`: Detection of long functions.
- `gocyclo`: Calculates  [cyclomatic complexities](https://en.wikipedia.org/wiki/Cyclomatic_complexity).
- `gosec`: Inspects source code for security problems.
- `lll`: Line length linter, used to enforce line length in files.

and I have added some directives to skip the checks with (`nolint`) because they need a small refactor but I think it's fine for now, we can improve it in the future.

Changes need in-depth review to make sure nothing is broken and that they are appropriate.

If you want to test this locally with https://github.com/nektos/act you'll have to add an additional step before `"Set up Go"` due to a dependencies error of the `nektos/act` default docker image.

```
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install gcc build-essential --assume-yes --quiet --no-install-suggests --no-install-recommends

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
```
Note I added a new step `golangci-lint` after `Build` step instead of adding a new workflow file as https://github.com/golangci/golangci-lint-action#how-to-use recommends, but in the future we could move it to its own file to have better control over the actions of the GitHub workflow.

I think the configuration is not very strict but it ensures a minimum quality of the code, if you consider it appropriate we can add other linters to make it more strict, but we have to think about it in order to facilitate the work of the collaborators in new pull requests.

We have an open discussion here.

I have do my best, I apologize in advance for any possible problems that may arise.

### CODE REVIEW

**Comment by Ice3man543** [comment]
@vzamanillo wow, this is amazing work! It'll take some more work to make things proper however this is a good start.

**Comment by vzamanillo** [comment]
> @vzamanillo wow, this is amazing work! It'll take some more work to make things proper however this is a good start.

Thank you very much @Ice3man543! as you said, it is a good start.

**Comment by Ice3man543** [comment]
@vzamanillo As it's a very big PR, give me some time to look over the changes. I'll work on this PR and merge this ASAP!

**Comment by vzamanillo** [comment]
> @vzamanillo As it's a very big PR, give me some time to look over the changes. I'll work on this PR and merge this ASAP!

Don't worry, we are not hurry, it is better to make sure nothing is broken before merge. Tell me if you need help with anything.

**Comment by vzamanillo** [comment]
https://github.com/golangci/golangci-lint-action/issues/23

**Comment by vzamanillo** [comment]
Hehehe, it works...

linting

**Comment by vzamanillo** [comment]
Can we merge this?, I have a lot of cool things on my mind but I am waiting to this PR has been released.

Do you need help to review it?

**Comment by bauthard** [comment]
Hi @vzamanillo, 

Thank you for confirming and letting us know, this PR is ready for the review and merge, we will this merge this in a day or two, thanks a lot for putting all the work on this.

**Comment by vzamanillo** [comment]
> Awesome work! Thanks a lot for cleaning up the code!

Thanks!

**Pull request merged**
