### PR TITLE
Integration test for sources w/o auth #649

### PR DESCRIPTION
**Pull request by dogancanbakir**
This PR adds integration tests for sources w/o [auth](https://github.com/projectdiscovery/subfinder/issues/649)

### CODE REVIEW

**Review by Ice3man543 — CHANGES_REQUESTED** [review]
@dogancanbakir the tests are failing for some reason. can you please fix them?

**Comment by forgedhallpass** [comment]
I've refactored the test to make detecting problems easier (will commit it later). The point is that based on that I've noticed that there are 3 or 4 providers that are not working currenlty. One has anti-automation (captcha) and 2 or 3 other services are not accessible anymore (gateway error and temporarily unavailabe).

**Comment by dogancanbakir** [comment]
@Ice3man543  As @forgedhallpass  pointed out, some of the providers are not working. Additionally, we should consider separating integration tests from the current pipeline, and maybe running them as a cron job might be a good idea.

**Comment by Ice3man543** [comment]
@forgedhallpass we should create issues regarding failing providers and ideally remove them since querying them is a waste of time.

**Comment by forgedhallpass** [comment]
> @forgedhallpass we should create issues regarding failing providers and ideally remove them since querying them is a waste of time.

That's was the plan, but only for tomorrow :)

**Pull request merged**
