### PR TITLE
fix(logging): label value should be a logging level

### PR DESCRIPTION
**Pull request by gnuletik**
This PR fixes the usage of the `Label(..)` function in gologger.

When Verbose mode is activated, and gologger is configured to use the JSON formatter, here are some logs printed by subfinder:

```
{"level":"dnsdumpster","msg":"rate-limited-proxy-108-177-77-100.google.com","timestamp":"2023-05-25T14:07:57+0000"}
{"level":"dnsdumpster","msg":"code.l.google.com","timestamp":"2023-05-25T14:07:57+0000"}
```

As you can see, the `level` value is incorrectly defined.
The level value should be one of the one defined by gologger:

https://github.com/projectdiscovery/gologger/blob/1fc5289842cc77b4c81dfef7b775cf3b25f97cdf/gologger.go#L15-L22

So, `dnsdumpster` is not the correct value.

This PR fixes the behavior by using logger fields to define the current fields.

### CODE REVIEW

**Comment by olearycrew** [comment]
Thanks for this contribution @gnuletik !

It looks like this PR would fix https://github.com/projectdiscovery/subfinder/issues/847

**Comment by gnuletik** [comment]
My pleasure! Yes it will fix this issue :)

**Comment by tarunKoyalwar** [comment]
hii @gnuletik , thanks for the PR but the original issue/feature seems to be gologger and it is being tracked here https://github.com/projectdiscovery/gologger/issues/38

ref: https://github.com/projectdiscovery/subfinder/issues/847#issuecomment-1564923150

**Comment by ehsandeep** [comment]
Thank you @gnuletik for opening this PR, closing this one as it will be addressed in the golagger project.

**Comment by gnuletik** [comment]
Hi @ehsandeep @tarunKoyalwar

I don't think that this issue should be addressed in gologger's https://github.com/projectdiscovery/gologger/issues/38

As I described in the initial description of this PR, gologger is just allowing its users to override the `level` value in the log fields (which may not be a good practice, especially without enum, but that's another subject).

However, subfinder is explicitly NOT using the label field properly, as it is not respecting gologger's defined labels value:
https://github.com/projectdiscovery/gologger/blob/1fc5289842cc77b4c81dfef7b775cf3b25f97cdf/gologger.go#L15-L22

This PR fixes the subfinder usage of subfinder.

**Comment by gnuletik** [comment]
@ehsandeep can you reconsider this PR please?

I really think that the underlying issue is about the usage of gologger in subfinder.

Thanks!

**Comment by ehsandeep** [comment]
@gnuletik see https://github.com/projectdiscovery/subfinder/issues/847#issuecomment-1569746389

**Pull request closed without merging**
