### PR TITLE
added subdomain.center

### PR DESCRIPTION
**Pull request by g147**

### CODE REVIEW

**Comment by olearycrew** [comment]
Hey @g147 thanks so much for this contribution!

**Comment by g147** [comment]
Hey @olearycrew,

Thanks to you too!

**Review by dogancanbakir — APPROVED** [review]
LGTM
```
$ go run . -d hackerone.com -s subdomaincenter

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/

                projectdiscovery.io

[INF] Current subfinder version v2.5.8 (outdated)
[INF] Loading provider config from /home/vscode/.config/subfinder/provider-config.yaml
[INF] Enumerating subdomains for hackerone.com
gsemail.hackerone.com
mta-sts.hackerone.com
o1.email.hackerone.com
links.hackerone.com
ns.hackerone.com
sts.hackerone.com
zendesk4.hackerone.com
b.ns.hackerone.com
design.hackerone.com
gslink.hackerone.com
mta-sts.forwarding.hackerone.com
zendesk3.hackerone.com
1.ns.hackerone.com
info.hackerone.com
managed.hackerone.com
api.hackerone.com
email.hackerone.com
sub.hackerone.com
forwarding.hackerone.com
go.hackerone.com
o2.email.hackerone.com
zendesk1.hackerone.com
25.hackerone.com
3d.hackerone.com
a.ns.hackerone.com
zendesk2.hackerone.com
invalid.hackerone.com
resources.hackerone.com
www.hackerone.com
mta-sts.managed.hackerone.com
test.hackerone.com
wwww.hackerone.com
support.hackerone.com
docs.hackerone.com
events.hackerone.com
o3.email.hackerone.com
[INF] Found 36 subdomains for hackerone.com in 552 milliseconds 636 microseconds
```

**Review by Mzack9999 — APPROVED** [review]
lgtm - I'm unable to rebase with `dev` as I don't have write permission on the fork and can't rerun the tests. Anyway the failures appears to be temporary of `riddler.io`

**Comment by ehsandeep** [comment]
@g147, Thank you for your contribution to the subfinder project. We've decided not to include the `subdomain.center` source for the time being due to its aggressive rate limit; we will revisit this source in the future.

**Pull request closed without merging**
