### PR TITLE
add subdomaincenter

### LINKED ISSUE #1309: Integration Request for Subdomain Center API
Hello!

Last year, I released an API called Subdomain Center. Due to its aggressive rate limits, which was the reason provided, it couldn't be integrating into the Subfinder project -  https://github.com/projectdiscovery/subfinder/pull/835

However, I have noticed that Subfinder now supports other providers with rate limits. Moreover, we now give rate limit free access to our paid users - https://www.arpsyndicate.io/pricing.html 

Given these updates, I believe it is now feasible to integrate the Subdomain Center API into Subfinder. 

API Details:
Endpoint: https://api.subdomain.center/
Documentation: https://github.com/ARPSyndicate/docs?tab=readme-ov-file#subdomain-center
Rate Limits: 2/minutes

I am confident that integrating Subdomain Center will enhance Subfinder's capabilities and provide users with more comprehensive results. Please let me know if there are any additional details or requirements needed for this integration.

Thanks!

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes #1309

```console
$ go run . -d hackerone.com -s subdomaincenter

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/

                projectdiscovery.io

[INF] Current subfinder version v2.6.6 (latest)
[INF] Loading provider config from /Users/dogancanbakir/Library/Application Support/subfinder/provider-config.yaml
[INF] Enumerating subdomains for hackerone.com
o3.email.hackerone.com
zendesk2.hackerone.com
cover-photos-user-content.hackerone.com
email.hackerone.com
links.hackerone.com
mta-sts.hackerone.com
profile-photos-user-content.hackerone.com
zendesk3.hackerone.com
a.ns.hackerone.com
design.hackerone.com
managed.hackerone.com
docs.hackerone.com
invalid.hackerone.com
ns.hackerone.com
o1.email.hackerone.com
support.hackerone.com
1.ns.hackerone.com
25.hackerone.com
api.hackerone.com
o2.email.hackerone.com
sub.hackerone.com
wwww.hackerone.com
zendesk1.hackerone.com
apis.hackerone.com
forwarding.hackerone.com
gslink.hackerone.com
b.ns.hackerone.com
events.hackerone.com
www.hackerone.com
3d.hackerone.com
info.hackerone.com
resources.hackerone.com
test.hackerone.com
gsemail.hackerone.com
mta-sts.forwarding.hackerone.com
mta-sts.managed.hackerone.com
zendesk4.hackerone.com
-tx1.hackerone.com
go.hackerone.com
sts.hackerone.com
[INF] Found 40 subdomains for hackerone.com in 527 milliseconds 17 microseconds
```

### CODE REVIEW

**Comment by dogancanbakir** [comment]
@g147 Hey there - got rate limit, see https://github.com/projectdiscovery/subfinder/actions/runs/9955674081/job/27503953251?pr=1315#step:5:1508.  Any idea why?

**Comment by g147** [comment]
Hello @dogancanbakir! No not sure exactly.

**Comment by dogancanbakir** [comment]
@g147 I'd like to merge this. As you can see from the code, we defined a '2/m' rate limit for the source, but we're getting `{"detail":"Rate limit exceeded: 2 per 1 minute"}`. I just want to know if it's possible to make the rate limit less aggressive.

**Comment by g147** [comment]
@dogancanbakir Have you tried rerunning the checks?

**Comment by dogancanbakir** [comment]
I ran twice and passed both times. Good.

**Comment by DhiyaneshGeek** [comment]
Hi @dogancanbakir 

i confirm this works well

```
subfinder -d hackerone.com -s subdomaincenter

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/

		projectdiscovery.io

[INF] Current subfinder version v2.6.6 (latest)
[INF] Loading provider config from /root/.config/subfinder/provider-config.yaml
[INF] Enumerating subdomains for hackerone.com
zendesk4.hackerone.com
3d.hackerone.com
cover-photos-user-content.hackerone.com
gsemail.hackerone.com
ns.hackerone.com
sts.hackerone.com
a.ns.hackerone.com
email.hackerone.com
mta-sts.hackerone.com
o1.email.hackerone.com
sub.hackerone.com
25.hackerone.com
b.ns.hackerone.com
go.hackerone.com
mta-sts.managed.hackerone.com
o3.email.hackerone.com
profile-photos-user-content.hackerone.com
zendesk3.hackerone.com
design.hackerone.com
managed.hackerone.com
-tx1.hackerone.com
apis.hackerone.com
gslink.hackerone.com
o2.email.hackerone.com
support.hackerone.com
www.hackerone.com
zendesk1.hackerone.com
1.ns.hackerone.com
events.hackerone.com
mta-sts.forwarding.hackerone.com
resources.hackerone.com
zendesk2.hackerone.com
wwww.hackerone.com
api.hackerone.com
docs.hackerone.com
forwarding.hackerone.com
info.hackerone.com
invalid.hackerone.com
links.hackerone.com
test.hackerone.com
[INF] Found 40 subdomains for hackerone.com in 276 milliseconds 694 microseconds
```

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
