### PR TITLE
Added flag to list all available sources

### PR DESCRIPTION
**Pull request by vzamanillo**
Implements #256

### CODE REVIEW

**Comment by bauthard** [comment]
Awesome! works perfectly @vzamanillo

**Comment by bauthard** [comment]
Hi @vzamanillo, 

Forgot to ask, do you already have access to [chaos](https://chaos.projectdiscovery.io) platforms? if not please fill your email [here](https://docs.google.com/forms/d/e/1FAIpQLSe5FBgtHoxgGPmJblsf50z1OAtecQWGJEn_Y8mF74T9dxjVxg/viewform) so we can extend an invitation to you.

**Comment by vzamanillo** [comment]
I have no access actually, thank you very much!

**Comment by vzamanillo** [comment]
@bauthard  I have an idea to identify and print which sources need an API key / token when `ls` is used.

ls

Do you think this is useful?

**Comment by bauthard** [comment]
Hey @vzamanillo, 

This is super useful, especially the warning message. +1 for this.

**Comment by vzamanillo** [comment]
> Hey @vzamanillo,
> 
> This is super useful, especially the warning message. +1 for this.

Great!

#273

**Pull request merged**
