### PR TITLE
Improved HTTP error handling

### PR DESCRIPTION
**Pull request by vzamanillo**
Implements #246

### CODE REVIEW

**Comment by vzamanillo** [comment]
I think treating any status code other than `200` as error is incorrect (ej: 302)

Should we consider that only the status codes in the 4xx or 5xx range are incorrect?

**Comment by bauthard** [comment]
Instead of `Invalid` or `error` we can use `Unexpected` word, do you think it's fair for 302 as well?

**Comment by vzamanillo** [comment]
> Instead of `Invalid` or `error` we can use `Unexpected` word, do you think it's fair for 302 as well?

Perfect!

**Comment by vzamanillo** [comment]
Last changes reveals that `digicert` source is not working anymore

digicert

digicert1

**Comment by vzamanillo** [comment]
`entrust` source too but looks like is due to maintenance

entrust

**Comment by vzamanillo** [comment]
Need help testing sources which needs API key or token (except `GitHub`) because I have not them. Could you please help me on this?.

**Comment by bauthard** [comment]
```
[virustotal] info.hackerone.com
[WRN] Could not run source entrust: Unexpected status code 403 received from https://ctsearch.entrust.com/api/v1/certificates?fields=issuerCN,subjectO,issuerDN,issuerO,subjectDN,signAlg,san,publicKeyType,publicKeySize,validFrom,validTo,sn,ev,logEntries.logName,subjectCNReversed,cert&domain=hackerone.com&includeExpired=true&exactMatch=false&limit=5000
[securitytrails] email.gh-mail.hackerone.com
[securitytrails] zendesk2.hackerone.com
[securitytrails] web-seo-content-for-business.theflyingkick.websitedesignresource.api.hackerone.com
[WRN] Could not run source binaryedge: Unexpected status code 403 received from https://api.binaryedge.io/v2/query/domains/subdomain/hackerone.com
[passivetotal] cf-ssl5349-protected-cover-photos-user-content.hackerone.com
[passivetotal] o1.email.hackerone.com
[passivetotal] go.hackerone.com
[passivetotal] cf-ssl5349-protected-profile-photos-user-content.hackerone.com
[passivetotal] o3.email.hackerone.com
[passivetotal] profile-photos-user-content.hackerone.com
[passivetotal] cf-ssl41462-protected-profile-photos-user-content.hackerone.com
[passivetotal] cover-photos-user-content.hackerone.com
[passivetotal] staging.hackerone.com
[passivetotal] cf-ssl41462-protected-cover-photos-user-content.hackerone.com
[crtsh] hackerone.com
[WRN] Could not run source archiveis: Get "http://archive.is/*.hackerone.com": dial tcp [2001:470:1f15:79a::acfd:f404]:80: connect: no route to host
[WRN] Could not run source commoncrawl: context deadline exceeded (Client.Timeout or context cancellation while reading body)
[threatminer] Source took 989.518896ms for enumeration
[WRN] Could not run source urlscan: Fail to get result query: Fail to unmarshal urlscan.io get result: json: cannot unmarshal number into Go struct field .meta.processors.wappa.data.categories.priority of type string
```

looks good to me, other errors are working as expected, in case of `binaryedge` I deliberately used invalid key, `archiveis` is blocked by local ISP, and `commoncrawl` got timed out, and `urlscan` API has it's own issue, so maybe we try to fix it or remove the source as the API is not officially maintained by the `urlscan` 

do you see anything else can be improved here? or let me know when this is ready to merge.

**Comment by vzamanillo** [comment]
I think the PR is ready to merge. About the `urlscan` source, we can open a new issue and discuss how to handle it there.

**Comment by bauthard** [comment]
We already have an issue for that at https://github.com/projectdiscovery/subfinder/issues/266

**Pull request merged**
