### PR TITLE
Retrieve archiveis first page

### PR DESCRIPTION
**Pull request by maldevel**
Archiveis is not working properly. When you are trying to retrieve the next page (e.g. https://archive.is/offset=50/*.github.com) you are getting an HTTP error 429 in golang because it asks for the user's input (recaptcha challenge solving). However, instead of removing the website completely you could just retrieve the results of the first page only.

### CODE REVIEW

**Review by ehsandeep — COMMENTED** [review]
@maldevel I see `503` status instead of `429`, is it expected after your change?

```sh
git branch --show-current
pr/445


./subfinder -d hackerone.com -v -sources archiveis

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/ v2.4.8

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
By using subfinder, you also agree to the terms of the APIs used.

[INF] Enumerating subdomains for hackerone.com
[WRN] Could not run source archiveis: unexpected status code 503 received from https://archive.is/*.hackerone.com
```

**Comment by maldevel** [comment]
I just tested it and it works. The 503 error means that the service wasn't available. Maybe it was temporarily unavailable on the server side? The HTTP 429 error code is being received when you try to capture the next page and it happens because of the recaptcha challenge.

**Comment by maldevel** [comment]
Sometimes you might receive http 429 error or other http errors because of the user agent string. The websites (not only archiveis) are blacklisting certain user agent strings and/or identical get/post requests that are being repeated in a short period of time. In that case, to solve this issue you have to change the user agent string in the agent.go file or preferably use a random user agent string with each http request.

**Review by Mzack9999 — APPROVED** [review]

**Comment by ehsandeep** [comment]
thank you @maldevel, I've created a separate issue to support user agent with each HTTP request.

**Pull request merged**
