### PR TITLE
BeVigil Source Added

### PR DESCRIPTION
**Pull request by alt-glitch**
BeVigil is a search engine for assets in mobile applications. They have released an API for extracting assets like subdomains, URL parameters for fuzzing for a given domain.

https://bevigil.com/osint-api

### CODE REVIEW

**Review by forgedhallpass — CHANGES_REQUESTED** [review]
It seems you've committed a binary. Please remove that.

**Comment by forgedhallpass** [comment]
Note: this PR will have to be squashed before merging in order not to pollute (and increase the size of) the history with the binary file that has been added by mistake and then removed in another commit.

**Review by forgedhallpass — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]

**Comment by forgedhallpass** [comment]
Depends on #588

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
lgtm - Needs rebase with https://github.com/projectdiscovery/subfinder/pull/588

**Pull request merged**
